/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-16 18:07:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tech.blog.entities.MessageServlet;
import com.tech.blog.helper.ConnectionProvider;
import java.sql.Connection;

public final class registration_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1720816988246L));
    _jspx_dependants.put("jar:file:/C:/Users/ranja/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/C:/Users/ranja/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1720207827750L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.tech.blog.helper.ConnectionProvider");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.tech.blog.entities.MessageServlet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" \n");
      out.write("              rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" \n");
      out.write("              crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("        <link href=\"CSS/registration_css.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("         <link href=\"CSS/mystyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!--navbar-->\n");
      out.write("            ");
      out.write("<nav class=\"navbar navbar-expand-lg primary-background\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"first.jsp\"><span class=\"fa fa-desktop\"></span> Tech Blog</a>\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Link</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Dropdown\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"login_page.jsp\"><span class=\"fa fa-user-circle\"></span> </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"registration_page.jsp\"><span class=\"fa fa-user-plus\"></span> </a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <form class=\"d-flex\" role=\"search\">\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("       \n");
      out.write(" \n");
      out.write("    <div class=\"wrapper\">\n");
      out.write("    <h2>Registration</h2>\n");
      out.write("    \n");
      out.write("    ");

            MessageServlet msg = (MessageServlet) session.getAttribute("msg");
            
               if(msg!=null)
               {
        
      out.write("\n");
      out.write("        <!--class=\"");
      out.print( msg.getStyle());
      out.write("\"-->\n");
      out.write("        <div  style=\"margin: 10px 0px 0px 0px; padding: 0px; color: ");
      out.print( msg.getType());
      out.write("\" align=\"center\">\n");
      out.write("           ");
      out.print( msg.getContent());
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");

               }
               
              session.removeAttribute("msg");

        
      out.write("\n");
      out.write("        \n");
      out.write("    <form action=\"RegisterServlet\" method=\"post\">\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"text\" name=\"user_name\" placeholder=\"Enter your name\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"text\" name=\"user_email\" placeholder=\"Enter your email\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"password\" name=\"user_password\" placeholder=\"Create password\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"password\" name=\"confirm_password\" placeholder=\"Confirm password\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("		<label>\n");
      out.write("			<input type=\"radio\" name=\"user_gender\" value=\"male\" checked/>\n");
      out.write("			<span>Male</span>\n");
      out.write("		</label>\n");
      out.write("		<label>\n");
      out.write("			<input type=\"radio\" name=\"user_gender\" value=\"female\" />\n");
      out.write("			<span>Female</span>\n");
      out.write("		</label>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"policy checkbox-wrapper-34\">\n");
      out.write("            <input class='tgl tgl-ios' id='toggle-34' name=\"checkbox\" type=\"checkbox\" value=\"accepted\" name=\"condition\">\n");
      out.write("            <label class='tgl-btn' for='toggle-34'></label>\n");
      out.write("            <h3> I accept all terms & condition </h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box button\">\n");
      out.write("            <input type=\"Submit\" value=\"Register Now\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"text\">\n");
      out.write("            <h3>Already have an account? <a href=\"login_page.jsp\">Login now</a></h3>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("<!--    \n");
      out.write("     <div class=\"wrapper form-div\">\n");
      out.write("    <h2>Registration</h2>\n");
      out.write("    <form action=\"RegServlet\" method=\"post\">\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"text\" name=\"user_name\" placeholder=\"Enter your name\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"text\" name=\"user_email\" placeholder=\"Enter your email\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"password\" name=\"user_password\" placeholder=\"Create password\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"input-box\">\n");
      out.write("            <input type=\"password\" placeholder=\"Confirm password\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("       <div class=\"container\">\n");
      out.write("	<form>\n");
      out.write("		<label>\n");
      out.write("			<input type=\"radio\" name=\"user_gender\" checked/>\n");
      out.write("			<span>Male</span>\n");
      out.write("		</label>\n");
      out.write("		<label>\n");
      out.write("			<input type=\"radio\" name=\"user_gender\"/>\n");
      out.write("			<span>Female</span>\n");
      out.write("		</label>\n");
      out.write("	</form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"policy\">\n");
      out.write("            <input type=\"checkbox\" value=\"accepted\" name=\"condition\">\n");
      out.write("            <h3>I accept all terms & condition</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box button\">\n");
      out.write("            <input type=\"Submit\" value=\"Register Now\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"text\">\n");
      out.write("            <h3>Already have an account? <a href=\"login_page.jsp\">Login now</a></h3>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</div>-->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" \n");
      out.write("        integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" \n");
      out.write("        crossorigin=\"anonymous\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
